Module 6: Tasks 1-3 have been solved with God's help
js-tasks-ru/jsbasic-20220711_hankko pull request #8
Opened 2022-08-12 22:25 UTC by flipexe

2022-08-12 22:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-13 09:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-13 09:38 UTC, SinimaWath requested changes

2022-08-13 09:38 UTC, SinimaWath commented on package.json
> +  "dependencies": {
А можешь убрать ненужные зависимости. Они у тебя как-то автоматом добавились

2022-08-13 09:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-13 12:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-14 20:02 UTC, SinimaWath requested changes

2022-08-14 20:02 UTC, SinimaWath commented on package.json
> -    "karma-viewport": "^1.0.6"
их нужно оставить

2022-08-14 20:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-14 20:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-14 20:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-15 02:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-15 10:31 UTC, SinimaWath commented
Все ок, просто осталось сделать остальные задачи :)

2022-08-15 12:16 UTC, flipexe commented
> Все ок, просто осталось сделать остальные задачи :)
Вот тут не понял, я пушил 6 модуль 1-3 задачи тесты проходили норм

2022-08-16 16:55 UTC, SinimaWath commented
Добавились остальные задачу, с последними коммитами

2022-08-19 18:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-19 18:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-19 19:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-20 12:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-20 13:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-21 13:42 UTC, SinimaWath approved these changes

2022-08-21 13:43 UTC, merged